<%_ if (!mongoDb) { _%>
spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
<%_ } _%>
logging:
  level:
    root: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: INFO